version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo/hitomi-client

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run lint
